{% set name = "igwn-ligolw" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/igwn_ligolw-{{ version }}.tar.gz
  sha256: 8cd3e9e45c76262c1b524068c1753c0c76e1e982c1972bc4d1f55e1e228b3db3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [win or python_impl != 'cpython']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    # extras for cross-compiling:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools >=64
    - setuptools-scm >=8
  run:
    - igwn-segments
    - numpy
    - python
    - python-dateutil
    - pyyaml
    - tqdm

test:
  requires:
    - pip
    - python-lal
  commands:
    # check metadata
    - python -m pip check
    - python -m pip show igwn-ligolw
    # sanity check scripts
    - igwn_ligolw_add --help
    - igwn_ligolw_cut --help
    - igwn_ligolw_no_ilwdchar --help
    - igwn_ligolw_print --help
    - igwn_ligolw_run_sqlite --help
    - igwn_ligolw_segments --help
    - igwn_ligolw_sqlite --help

about:
  summary: Python LIGO Light-Weight XML I/O Library
  home: https://git.ligo.org/computing/software/igwn-ligolw/
  dev_url: https://git.ligo.org/computing/software/igwn-ligolw.git
  doc_url: https://igwn-ligolw.readthedocs.io
  license: GPL-3.0-or-later
  license_file: LICENSE
  description: |
    The LIGO Light-Weight XML format is used extensively by compact object
    detection pipeline and associated tool sets.
    This package provides a Python I/O library for reading, writing, and
    interacting with documents in this format.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - lpsinger
    - titodalcanton
